const levelsObj = {
  level1: {
    grid: [
      [
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
      ],
      [
        "border",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        "blocker",
        "blocker",
        "blocker",
        "blocker",
        "blocker",
        "blocker",
        "blocker",
        " ",
        "blocker",
        "blocker",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        "blocker",
        "green",
        " ",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        "blocker",
        "green",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        "blocker",
        "blocker",
        " ",
        "blocker",
        "blocker",
        "blocker",
        "blocker",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        " ",
        " ",
        " ",
        "blocker",
        " ",
        " ",
        " ",
        "blocker",
        " ",
        " ",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        "blocker",
        "blocker",
        " ",
        " ",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        " ",
        " ",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        " ",
        " ",
        " ",
        "blocker",
        "green",
        "border",
      ],
      [
        "border",
        " ",
        "blocker",
        " ",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        " ",
        "blocker",
        " ",
        " ",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        "blocker",
        "green",
        " ",
        " ",
        " ",
        "blocker",
        "blocker",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        " ",
        "blocker",
        "blocker",
        " ",
        " ",
        "blocker",
        " ",
        " ",
        "blocker",
        " ",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        "blocker",
        " ",
        " ",
        " ",
        " ",
        "blocker",
        "blocker",
        " ",
        "blocker",
        "blocker",
        " ",
        "blocker",
        " ",
        "border",
      ],
      [
        "border",
        " ",
        "blocker",
        "blocker",
        " ",
        "blocker",
        " ",
        " ",
        " ",
        "blocker",
        " ",
        " ",
        " ",
        "blocker",
        "border",
      ],
      [
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
        "border",
      ],
    ]
  },
};

export default levelsObj;
